server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]": # 모든 경로에 대한 CORS 설정을 시작하겠다.
            allowed-origins:
              - "로컬 서버 연결 호스트 주소"
              - "aws 연결된 url 주소"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers:
              - Content-Type
              - Authorization
              - X-Requested-With # AJAX 요청임을 표시 (우리가 세팅하는 건 아님)
            allow-credentials: true # 인증 정보 포함 요청을 허용하겠다.

      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: hello gateway!
            preLogger: false
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}