server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]": # 모든 경로에 대한 CORS 설정을 시작하겠다.
            allowed-origins:
              - "http://localhost:5173"
              - "http://artlog-s3-front-end-1733.s3-website-ap-southeast-2.amazonaws.com"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers:
              - Content-Type
              - Authorization
              - X-Requested-With # AJAX 요청임을 표시 (우리가 세팅하는 건 아님)
            allow-credentials: true # 인증 정보 포함 요청을 허용하겠다.

      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: hello gateway!
            preLogger: false
            postLogger: true
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user/**
          filters:
            - name: GlobalFilter
              args:
                baseMessage: pass
                preLogger: true
                postLogger: true
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: coupon-service
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/coupon-service/coupon/**
          filters:
            - name: GlobalFilter
              args:
                baseMessage: pass
                preLogger: true
                postLogger: true
            - RewritePath=/coupon-service/(?<segment>.*), /$\{segment}

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/review/**
          filters:
            - name: GlobalFilter
              args:
                baseMessage: pass
                preLogger: true
                postLogger: true
            - RewritePath=/review-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationHeaderFilter
#
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/order/**
          filters:
            - name: GlobalFilter
              args:
                baseMessage: pass
                preLogger: true
                postLogger: true
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationHeaderFilter
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
